# Generated by Django 4.1 on 2024-03-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="foods",
            name="soup",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="questions",
            name="answer",
            field=models.IntegerField(),
        ),
    ]
