# Generated by Django 4.1 on 2024-04-02 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_foods_soup_alter_questions_answer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questions",
            old_name="answer",
            new_name="answerFromAnsTable",
        ),
        migrations.RemoveField(
            model_name="foods",
            name="origin",
        ),
        migrations.AddField(
            model_name="foods",
            name="carb",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="foods",
            name="category",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="foods",
            name="soup",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="foods",
            name="temperature",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="questions",
            name="question",
            field=models.TextField(max_length=300),
        ),
        migrations.CreateModel(
            name="answers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.IntegerField()),
                (
                    "answer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.questions"
                    ),
                ),
            ],
        ),
    ]
