# Generated by Django 4.1 on 2024-04-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_foods_spiciness_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answers",
            name="answer",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="questions",
            name="answerFromAnsTable",
            field=models.BooleanField(null=True),
        ),
    ]
