# Generated by Django 4.1 on 2024-04-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_answers_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="answerFromAnsTable",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
